sudo: false
language: node_js
cache:
  directories:
    - node_modules
script:
  - cd demo
  - yarn
  - ng build --prod --base-href "https://preeco-privacy.github.io/"
  - ngh --no-silent --branch master  --dir dist/demo --repo=https://GH_TOKEN@github.com/preeco-privacy/preeco-privacy.github.io --name="preeco-privacy" --email=info@preeco.de
notifications:
  email: false
node_js:
  - '10'
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g npm@^3
before_script:
  - npm prune
  - export DISPLAY=:99.0
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
